package sv.com.lc.controlac.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DetallesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetallesAllPropertiesEquals(Detalles expected, Detalles actual) {
        assertDetallesAutoGeneratedPropertiesEquals(expected, actual);
        assertDetallesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetallesAllUpdatablePropertiesEquals(Detalles expected, Detalles actual) {
        assertDetallesUpdatableFieldsEquals(expected, actual);
        assertDetallesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetallesAutoGeneratedPropertiesEquals(Detalles expected, Detalles actual) {
        assertThat(expected)
            .as("Verify Detalles auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetallesUpdatableFieldsEquals(Detalles expected, Detalles actual) {
        assertThat(expected)
            .as("Verify Detalles relevant properties")
            .satisfies(e -> assertThat(e.getCantidad()).as("check cantidad").isEqualTo(actual.getCantidad()))
            .satisfies(e -> assertThat(e.getTotal()).as("check total").isEqualTo(actual.getTotal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetallesUpdatableRelationshipsEquals(Detalles expected, Detalles actual) {
        // empty method
    }
}
